site_name: Indihu Exhibition
theme: 
  name: material
  language: 'cs'
nav:
    - 'Úvod': 'index.md'
    - 'Koncepce editoru': 'koncepce-editoru.md'
    - 'Základní fungování': 'zaklady.md'
    - 'Vytváříme obsah výstavy': 'obsah-vystavy.md'  
    - 'Obrazovky': 'obrazovky.md'
    - 'Hry': 'hry.md'
    - 'Inspirace': 'inspirace.md'
repo_url: https://nnis.github.io/indihu-manual/
markdown_extensions:
  - toc:
      permalink: '#'
  - admonition

